export enum MenuItems {
  Dashboard = 'Dashboard',
  Categories = 'Categories',
  Posts = 'Posts',
  CreatePost = 'Create Post',
  UpdatePost = 'Update Post',
  MyPosts = 'My Posts',
  Profile = 'Profile',
  Settings = 'Settings',
  Home = 'Home',
  Logout = 'Logout',
  Login = 'Login',
}

export enum Routes {
  Dashboard = '/dashboard',
  Categories = '/category',
  Posts = '/posts',
  CreatePost = '/posts/create',
  UpdatePost = '/posts/update/:id',
  Profile = '/profile',
  Settings = '/settings',
  Home = '/',
  Logout = '/logout',
  Login = '/login',
  Signup = '/signup',
  UserProfile = '/userprofile',
  PostWithId = '/posts/:id',
  UserWithId = '/users/:id',
  Unauthorized = '/unauthorized',
  MyPosts = '/myposts',
}
